environment_name = "bootcamp"
location = "West Europe"
account_kind = "StorageV2"
account_tier = "Standard"
account_replication_type = "LRS"
is_hns_enabled = "false"
enable_https_traffic_only = "false"